<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="DebugApp.xaml" />
    <Resource Include="Resources\Icons.xaml" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Develoh.BIM.RVT25\Develoh.BIM.RVT25.csproj" />
    <ProjectReference Include="..\RevitMcp.Contracts\RevitMcp.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2025.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath);$(TargetDir)RevitMcp.Contracts.dll;$(TargetDir)Develoh.BIM.RVT25.dll" DestinationFolder="C:\ProgramData\Autodesk\Revit\Addins\2025\" />
  </Target>

</Project>
